services:
  phpSeplag:
    container_name: php-seplag
    build:
      context: ./docker
    image: php-seplag
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/docker-php.ini
    restart: unless-stopped
    networks:
      - docker-network

  nginx:
    container_name: nginx-seplag
    hostname: seplag.local
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    depends_on:
      - phpSeplag
    restart: unless-stopped
    networks:
      - docker-network

  postgres17:
    image: postgres:17.4
    hostname: postgres17
    container_name: postgres17
    environment:
      POSTGRES_DB: seplag
      POSTGRES_PASSWORD: seletivo_seplag
      POSTGRES_USER: root
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./docker/pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: unless-stopped
    networks:
      - docker-network

  minio:
    container_name: minio-seplag
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: seletivo_seplag
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - docker-network

  minio-setup:
    container_name: minio-setup
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 admin seletivo_seplag &&
      mc mb --ignore-existing myminio/seplag &&
      exit 0
      "
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
